"use client";
import { useEffect,useMemo,useRef } from "react";
import { geoGraticule10,geoOrthographic,geoPath } from "d3-geo";
import { feature } from "topojson-client";
import world from "world-atlas/countries-110m.json";

export const locations=[{name:"UAE",lat:24.45,lon:54.38},{name:"INDIA",lat:20.59,lon:78.96},{name:"SINGAPORE",lat:1.35,lon:103.82},{name:"GERMANY",lat:51.17,lon:10.45},{name:"UNITED KINGDOM",lat:55.38,lon:-3.44},{name:"UNITED STATES",lat:37.09,lon:-95.71},{name:"CHINA",lat:35.86,lon:104.2},{name:"SOUTH AFRICA",lat:-30.56,lon:22.94}];

export default function GlobeCanvas({active}:{active:number}){
  const canvasRef=useRef<HTMLCanvasElement>(null);
  const liveActive=useRef(active);
  const land=useMemo(()=>feature(world as never,(world as {objects:{countries:never}}).objects.countries),[]);
  const state=useRef({lon:locations[0].lon,lat:locations[0].lat,zoom:1,targetLon:locations[0].lon,targetLat:locations[0].lat,targetZoom:1.2});
  useEffect(()=>{liveActive.current=active;const place=locations[active];state.current.targetLon=place.lon;state.current.targetLat=place.lat;state.current.targetZoom=1.17+(active%3)*.06},[active]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;let raf=0;const projection=geoOrthographic().clipAngle(90);const path=geoPath(projection,ctx);const graticule=geoGraticule10();const resize=()=>{const dpr=Math.min(devicePixelRatio,2),rect=canvas.getBoundingClientRect();canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};const draw=()=>{const{width:w,height:h}=canvas.getBoundingClientRect();state.current.lon+=(state.current.targetLon-state.current.lon)*.035;state.current.lat+=(state.current.targetLat-state.current.lat)*.035;state.current.zoom+=(state.current.targetZoom-state.current.zoom)*.035;const radius=Math.min(w,h)*.43*state.current.zoom;projection.translate([w/2,h/2]).scale(radius).rotate([-state.current.lon,-state.current.lat*.72,0]);ctx.clearRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.42,h*.38,0,w/2,h/2,radius*1.2);glow.addColorStop(0,"rgba(245,182,42,.19)");glow.addColorStop(.72,"rgba(245,182,42,.035)");glow.addColorStop(1,"transparent");ctx.fillStyle=glow;ctx.beginPath();ctx.arc(w/2,h/2,radius*1.16,0,Math.PI*2);ctx.fill();ctx.beginPath();path({type:"Sphere"});ctx.fillStyle="rgba(6,29,51,.3)";ctx.fill();ctx.strokeStyle="rgba(247,245,239,.28)";ctx.lineWidth=1.3;ctx.stroke();ctx.beginPath();path(graticule);ctx.strokeStyle="rgba(247,245,239,.09)";ctx.lineWidth=.8;ctx.stroke();ctx.beginPath();path(land);ctx.fillStyle="rgba(247,245,239,.055)";ctx.fill();ctx.strokeStyle="rgba(247,245,239,.72)";ctx.lineWidth=1.15;ctx.stroke();locations.forEach((place,i)=>{const point=projection([place.lon,place.lat]);if(!point)return;const center=projection.invert?.([w/2,h/2]);if(center){const lonDelta=Math.abs((((place.lon-center[0])+540)%360)-180);if(lonDelta>90)return}const on=i===liveActive.current;ctx.beginPath();ctx.arc(point[0],point[1],on?7:3,0,Math.PI*2);ctx.fillStyle=on?"#f5b62a":"rgba(247,245,239,.75)";ctx.fill();if(on){ctx.strokeStyle="#f5b62a";ctx.lineWidth=1;ctx.beginPath();ctx.arc(point[0],point[1],15,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#f7f5ef";ctx.font="700 11px Manrope";ctx.fillText(place.name,point[0]+22,point[1]+4)}});raf=requestAnimationFrame(draw)};resize();addEventListener("resize",resize);draw();return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize)}},[land]);
  return <canvas className="globe-canvas" ref={canvasRef}/>;
}
